### ISSUE TITLE
Replace reference to AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.1

### ISSUE THREAD

**Issue by anhaehne** [wertzui/RESTworld#3]
AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.1 has been deprecated so 12.0.0 should be used to not strictly reference AutoMapper 12.0.1.

- AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.1 references AutoMapper **=** 12.0.1
- AutoMapper.Extensions.Microsoft.DependencyInjection 12.0.0 references AutoMapper **>** 12.0.0

Otherwise you can upgrade to AutoMapper 13.0.0 wich has the DI registration baked in. See https://docs.automapper.org/en/latest/13.0-Upgrade-Guide.html

**Comment by wertzui** [comment]
This has been fixed in RESTworld.Business 15.0.0 which is used by RESTworld.AspNetCore 24.0.0 and RESTworld.Client.AspNetCore

AutoMapper.Extensions.Microsoft.DependencyInjection has been removed and
AutoMapper has been upgraded to 13.0.1
