### ISSUE TITLE
Provide an alternative to StartupBase for the minimal hosting model

### ISSUE THREAD

**Issue by anhaehne** [wertzui/RESTworld#4]
When using the newer minimal hosting model there is no startup class anymore.
There should be alternatives providing extension methods for `IHostApplicationBuilder`.

This is needed to provide native support for .net Aspire.

**Comment by wertzui** [comment]
RESTworld.AspNetCore 24.0.0 and RESTworld.Client.AspNetCore 17.0.0 are now using WebApplicationBuilder.

When calling  `builder.AddRestWorld();`, an instance of `RestWorldApplicationBuilder` is returned which is needed to call `AddODataModelForDbContext<TDbContext>()`. For the rest, `RestWorldApplicationBuilder` behaves just like `WebApplicationBuilder` and it does not matter which one is used in any other cases.
